- name: Remove apache servers
  hosts: webservers
  tasks: 
    - name: Remove apache server fron webservers
      ansible.builtin.yum:
        name: httpd
        state: absent
        autoremove: yes

- name: Remove apache servers from ubuntuservers
  hosts: ubuntuservers
  tasks: 
    - name: Remove apache servers from ubuntuservers
      ansible.builtin.apt:
        name: apache2
        state: absent
        autoremove: yes
        purge: yes
          